### ISSUE TITLE
Warning: could not load plugin. See `rio segment --help` ?

### ISSUE THREAD

**Issue by CosmosEcho** [mparker2/rio-segment#1]
The plugin is not working.
Warning: entry point could not be loaded. Contact its author for help.

  Traceback (most recent call last):
    File "D:\py_env\flask_env\lib\site-packages\click_plugins\core.py", line 37, in decorator
      group.add_command(entry_point.load())
    File "D:\py_env\flask_env\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
      return self.resolve()
    File "D:\py_env\flask_env\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "build\bdist.win-amd64\egg\rio_segment\__init__.py", line 5, in <module>
    File "build\bdist.win-amd64\egg\rio_segment\split.py", line 9, in <module>
    File "D:\py_env\flask_env\lib\site-packages\skimage\__init__.py", line 167, in <module>
      from .util.dtype import (img_as_float32,
    File "D:\py_env\flask_env\lib\site-packages\skimage\util\__init__.py", line 6, in <module>
      from .apply_parallel import apply_parallel
    File "D:\py_env\flask_env\lib\site-packages\skimage\util\apply_parallel.py", line 8, in <module>
      import dask.array as da
    File "D:\py_env\flask_env\lib\site-packages\dask\array\__init__.py", line 9, in <module>
      from .routines import (take, choose, argwhere, where, coarsen, insert,
    File "D:\py_env\flask_env\lib\site-packages\dask\array\routines.py", line 256, in <module>
      @wraps(np.matmul)
    File "c:\python27\python2.7.10\Lib\functools.py", line 33, in update_wrapper
      setattr(wrapper, attr, getattr(wrapped, attr))
  AttributeError: 'numpy.ufunc' object has no attribute '__module__'

**Comment by mparker2** [comment]
Sorry I don't really work on this anymore so won't be able to help much. From the error though it looks like you have incompatible versions of numpy and dask, which are dependencies of skimage.

**Comment by CosmosEcho** [comment]
Is what you said that the plugin is not running anymore? Oh, it is so bad. Your two result pictures look very nice.That is the effect and job which i want to do.
Thinks for your reply.
